CREATE TABLE TB_CLIENTE (
	
    ID_CLIENTE 			INT PRIMARY KEY AUTO_INCREMENT,
	NM_NOME 			VARCHAR(200),
    DS_EMAIL			VARCHAR(200),
    DS_TELEFONE			VARCHAR(16),
    DS_CPF				VARCHAR(150),
    DS_CNH				VARCHAR(150)
    
);

